Typescript Support, Build Optimizations, Bug Fixes and Feature Request
uptick/react-object-list pull request #125
Opened 2021-05-26 07:49 UTC by dreadera

### **The Problem**
First of all I Apologize for the large chunk of changes. I tried to minimize it as much as possible.
This entire library has been stuck in a bit of a time machine. It's quite dated with failing tests, mismatched versioning and lack of proper development tools.

**The List of Problems:**
- Lack of TypeScript Support
- Failing Builds
- Failing Tests
- Webpack
- Chunky Bundle
- No Currency Support for the Currency Type Filter

### **The Goal**
- Update dependencies.
- Introduce new building tools.
- TypeScript support.
- Fix the buggy tests
- Add Multiple Currency / Locale Number Formatting

### **What has been done**
- Introduced Rollup as our default bundler. 
- Introduced TypeScript support.
- Introduced the useLocaleNumber hook.
- Introduced new Currency Filter Type Component.
- Introduced React Context Provider to act as a store.
- Existing Test Cases Updated.
- Existing Storybooks Updated.
- New Tests cases Added.
- Updated Storybooks.
- Updated Version Number.
- Dependency Clean up

2021-05-27 23:06 UTC, uptickmetachu commented
My slight concern is we are going from one ball of complexity to another (webpack -> rollup). There seems to be equally a lot of configuration required WRT babel/eslint/rollup as there was before. 

I do appreciate the better build times and bundle size. I wonder if there is a way to simplify the build? Also have we tested this with `yarn link` against workforce to make sure the built version works with workforce (minus the janky stuff in workforce webpack).

2021-05-27 23:14 UTC, uptickmetachu reviewed
Same as my comments above, otherwise looking good!

Regarding the actual frontend changes can you add a comment to sections that reviewers should look at? It has become hard to navigate due to all the format changes.

2021-05-27 23:14 UTC, uptickmetachu commented on package.json
> +    "typescript-eslint": "^0.0.1-alpha.0"
o,o is this the correct plugin? 
https://www.npmjs.com/package/@typescript-eslint/eslint-plugin
Perhaps we mean this one?

2021-05-27 23:14 UTC, uptickmetachu commented on rollup.config.js
> +      file: packageJson.main,
oh neat! I like this importing the package.json and referencing the file for linking the build tools to the packaging. 👍🏼

2021-05-27 23:14 UTC, uptickmetachu commented on rollup.config.js
> +    // Do Babel transpilation.
:( Somehow I assumed we could get rid of babel if we adopted TS.

2021-05-27 23:29 UTC, dreadera commented on package.json
> +    "typescript-eslint": "^0.0.1-alpha.0"
oops, you're right. I will rectify this :)

2021-05-27 23:41 UTC, dreadera commented on rollup.config.js
> +    // Do Babel transpilation.
I fully agree that going from webpack -> rollup doesn't change things in terms of configuration and does add a bit of complexity if you don't know rollup but i chose it simply for the sake of having a large amount of community maintained plugins that work out of the box without much configuration. while the actually rollup config itself does require you incorporate the plugins, the plugins themselves don't need much configuration. 

if it makes things easier, we can try esbuilding everything without having rollup :) the configuration is also minimal for that :))

2021-05-27 23:42 UTC, dreadera commented
I fully agree that going from webpack -> rollup doesn't change things in terms of configuration and does add a bit of complexity if you don't know rollup but i chose it simply for the sake of having a large amount of community maintained plugins that work out of the box without much configuration. while the actually rollup config itself does require you incorporate the plugins, the plugins themselves don't need much configuration.

if it makes things easier, we can try esbuilding everything without having rollup :) the configuration is also minimal for that :))

2021-05-27 23:45 UTC, dreadera commented
In terms of testing with workforce, I haven't fully tried every place where this library is used but I did yarn link and have a go on a demo version I setup, which worked as intended :)

2021-05-28 00:45 UTC, adamdickinson requested changes
Relatively quick pass from me. Awesome attention to detail in many parts - loving what you've done! I've noted a few things, queried a few parts and suggested some things along the way.

I will flag that I'm concerned we won't be able to give this a thorough and proper review due to its size, but I'll do my best :)

Also apologies for the short/sharp/inconsiderate comments! Loving your work, just short on time this morning 😬.

2021-05-28 00:45 UTC, adamdickinson commented on src/filters/types/__tests__/Date.test.js
> +import { snapshotTest } from '../../../../utils/tests'
Out of curiosity - what benefit do we get from switching away from the aliased paths?

2021-05-28 00:45 UTC, adamdickinson commented on src/filters/types/__tests__/__snapshots__/Currency.test.js.snap
> +exports[`Currency Snapshots enders default 1`] = `
Typo?

2021-05-28 00:45 UTC, adamdickinson commented on src/filters/types/__tests__/__snapshots__/currency.test.tsx.snap
> +exports[`Currency Snapshots enders default 1`] = `
Typo here too?

2021-05-28 00:45 UTC, adamdickinson commented on src/hooks/use-locale-number.test.tsx
> +describe('Convert Number To Locale', () => {
Question on consistency - we use lowercase in our other test files, but Title Case throughout this one. I think the convention is the former. Could we update to lowercase to stay with convention?

```suggestion
describe('convert number to locale', () => {
```

2021-05-28 00:45 UTC, adamdickinson commented on src/hooks/use-locale-number.ts
> +    ...params,
I think you've done a good enough job making the code explain this for you :)
```suggestion
    ...context,
    ...params,
```

2021-05-28 00:45 UTC, adamdickinson commented on src/hooks/use-locale-number.ts
> +  }
Could we default to 0 to simplify this?

```suggestion
  function format(value = 0) {
    return new Intl.NumberFormat(locale, options).format(value)
  }

  return {
    format,
    configuration,
  }
```

2021-05-28 00:45 UTC, adamdickinson commented on src/utils/translate.ts
> +}
What... does this function do?

2021-05-28 00:53 UTC, dreadera commented on src/utils/translate.ts
> +}
Ah, I forgot to remove this. I was planning to write a locale function to get strings from objects. like lodash/get. however, i moved away from this. I just forgot to remove the function.

2021-05-28 00:54 UTC, dreadera commented on src/hooks/use-locale-number.ts
> +  }
Oh for sure, this makes more sense! :)

2021-05-28 00:58 UTC, dreadera commented on package.json
> +  "version": "0.3.00",
I only changed the middle value to represent the minor update in accordance with SemVer to represent the new currency feature.

2021-05-28 00:58 UTC, dreadera commented on src/ObjectList.demo.stories.js
> +const mockData = require('../samples/people.json')
We should. Faker is really nice for dev / showcasing :)

2021-05-28 01:00 UTC, dreadera commented on .eslintrc
> +  "plugins": ["babel", "react", "react-hooks", "@typescript-eslint"],
I was thinking the same thing. I think we should all have a standardised version which should be version controlled and then be available via npm :)

2021-05-28 01:58 UTC, jarekwg requested changes
I'm not strong on reviewing frontend code, so just going to provide cursory comments.
- The size of this PR is very hard to review properly. If it's relatively straightforward to cut a couple more branches from master, cherry pick individual changes into them, and open up a couple of smaller PRs. This is especially important when it comes to codestyle changes vs business logic changes. At the very least, the currency changes need to be moved out of here and done separately.
- My vote would be to use esbuild over rollup here too, just so that we're not spreading ourselves thing on bundler prerequisite knowledge..

2021-05-28 01:58 UTC, jarekwg commented on src/filters/types/Currency.tsx
> +}
This doesn't look right -- "currencySymbol" suggests '$', not 'AUD'..
The way I'd see this working is the widget reads in locale info from a higher context, and then applies the appropriate

2021-05-28 02:24 UTC, dreadera commented on src/filters/types/Currency.tsx
> +}
The native Intl.NumberFormat function takes in the standard currency symbols.

This works a lot better as it's built into JS and means we only have to provide the following. Locale, Currency Format and Decimals to the context provider upon invocation.  

Function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
List: https://www.currency-iso.org/en/home/tables/table-a1.html

2021-05-28 02:25 UTC, dreadera commented
I 100% agree that this was should have been broken down into multiple PRs. I do apologise for that.

2021-05-28 04:50 UTC, jarekwg commented on src/filters/types/Currency.tsx
> +}
gotcha; can we rename it just to `currency` then?

2021-05-28 04:53 UTC, jarekwg commented
Ok, if not planning to split this up, we'll want to publish this with at least a minor version release bump (ie 0.3.0). Then will probs be best to test by plugging it directly into workforce and clicking through to see how it all works. I suspect there'll need to be followup patch versions needed for the stuff we haven't picked up in this review.

2021-06-01 07:00 UTC, scaredcat commented
The changes here won't quite work. This package is set up kind of like a PWA where
* `src/index` is the skeleton app. Placeholders for the filers (top section) and renderer (table/list)
* `src/filters/index` is the filters to display at the top of the app
* `src/data-renderers/index` is the content of the app (also imported directly into the skeleton app -- bad practice, but programmers are lazy. 99% of the time we will use Table renderer)
* `src/icons` -- us trying to be fancy with too much customization. We should just use one icon set and stick with that.
* `src/types` aka cells -- fine grained control of the type of data rendered within a table

In your changes `rollup.config.js` only references `src/index` which also includes the default data renderer and probably some cells. Its tree-shaking functionality is quite good so it will get rid of things that are not exported/referenced.

Please either
1. Export all the things from `src/index` to make sure it comes with all the necessary parts (preferred option)
2. Update rollup to continue delivering this package as a Frankenstein for self-assembly at the other end

2021-06-01 11:25 UTC, dreadera commented
wow, thanks for all that. it's nice to get some feedback on someone who worked on it :)
I'll improve this PR with the notes you have given. Thank you @scaredcat

2022-01-24 22:52 UTC, closed without merging